### ISSUE TITLE
Question. Multiple entries

### ISSUE THREAD

**Issue by chemitaxis** [icflorescu/quickstart-express-react#2]
Hi I like a lot the concept of this boilerplate... I would like to know how to have multiple entries for the webpack config.

I dont need to use react router and redux, just react, but I would like to have one .js for each page, and a common vendors js. If this possible?

I have created a question in StackOverflow: http://stackoverflow.com/q/42213694/1147273

Thanks and excellent work!!

**Comment by icflorescu** [comment]
Hi, Chema, and thanks for the nice words!

Yeah, it's definitely possible and I've updated the repo to better illustrate this and pushed  Basically you'll just have to add items to the `entry` object in `webpack.config.js` - currently [these lines](https://github.com/icflorescu/quickstart-express-react/blob/master/webpack.config.js#L7-L14) after the last commit.

**Comment by icflorescu** [comment]
I've also replied to the question on SO :-)

Is it ok if I close this issue? I've marked it as a question, since other people might benefit from it.

**Comment by chemitaxis** [comment]
Perfect! Thanks!! ;)
