### ISSUE TITLE
loader-utils deprecation warning

### ISSUE THREAD

**Issue by viglucci** [icflorescu/quickstart-express-react#3]
babel-loader prior to babel-loader@7.0.0 results in a deprecation warning from loader-utils@0.2.17.

```
(node:14064) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

Updating to babel-loader@7.0.0 seemed to resolve this and i'm not aware of any side effects.

**Comment by icflorescu** [comment]
Hi @viglucci,

Thanks for raising the issue. I've updated most deps in the latest commits, everything should be fine now.

I'm not using this quickstart in my work anymore, so - a quick question: would you be interested in becoming a maintainer?

**Comment by viglucci** [comment]
Thanks for making those updates @icflorescu.

Though I have a fork of this repository and i'm working on flushing out the example and adding more features as a learning opportunity, i'm not sure I would be too helpful as as maintainer as my React & Webpack skills are very junior at the moment. If I become more familiar with React & Webpack as I work through this exercise, I may become more open to becoming a maintainer (though hopefully not the sole maintainer).

I will say I very much appreciate you putting together this example / quick start as I have historically been frustrated with the many examples and tutorials that neglect the potential for a projects needs to include both traditional server side rendering as well as more convention single page behavior.

Out of curiosity, have you moved on from this project due to developing a superior solution? Or is this project simply no longer relevant for your needs?

**Comment by icflorescu** [comment]
Well, I'm far from pretending to be a React & Webpack guru myself; I only started to play with both of them last year :-).

Regarding a potentially superior solution, you can have a look at this [universal-react](https://github.com/icflorescu/quickstart-universal-react) starter. It's not necessarily superior, just different – based on the single tutorial I could find that really explained how to set up a server-side-rendered solution with React (there's a link in the README there). There are drawbacks, of course (i.e. rendering React on the server will always be slower than using template engines), but  using the same stack on both the server and the client sounds convenient, so I've decided to try it in my next project.
